### ISSUE TITLE
When the title contains Chinese, an error will be reported

### ISSUE THREAD

**Issue by myface-wang** [meilisearch/docs-searchbar.js#117]

**Comment by myface-wang** [comment]
![20200906132002](https://user-images.githubusercontent.com/13325359/92318804-03c66f00-f044-11ea-9519-5c2d9149802d.png)
But the official plug-ins don't have this problem
@vuepress/plugin-search
and i know algolia have this problem

**Comment by curquiza** [comment]
Hello @myface-wang!

Sorry for this issue. @vuepress/plugin-search does not need to search engine in background to work. It only searches through the existing content, but it's not typo-tolerant and not as relevant as MeiliSearch or Algolia.
As [we mention it in our README](https://github.com/meilisearch/docs-searchbar.js#credits), docs-searchbar.js is strongly based on the Algolia's work. That might explain why we also have the same issue.

I let this issue open anyway since it should not be present!

**Comment by bidoubiwa** [comment]
Hey @myface-wang,
could you provide a link to your documentation so that we can test it out?

**Comment by myface-wang** [comment]
> Hey @myface-wang,
> could you provide a link to your documentation so that we can test it out? Does your `classes` and `id` contain chinese characters ?
> 
> This might be a fix : https://stackoverflow.com/questions/47352873/can-i-use-chinese-characters-in-css-class-names

yes，I changed the code
```
decodeURI(`${routepath}${hash}`)
```

**Comment by bidoubiwa** [comment]
Did it work ?

**Comment by myface-wang** [comment]
> Did it work ?

Yes, it works

**Comment by curquiza** [comment]
Closing this issue then 🙂
