### ISSUE TITLE
Remove dupicated version mention

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/docs-searchbar.js#361]
Version are both changed in `package.json` and `version.js`.

Creating a duplication of changes in each release. `version.js` is used by `src/lib/main.js`

```js
import toFactory from 'to-factory'
import DocsSearchBar from './DocsSearchBar'
import version from './version'
```

We should find a solution to avoid this duplication

**Comment by sanders41** [comment]
You can get the version from the `package.json` file like below, but the **BIG** caveat is this ships the whole `package.json` file to the client and therefore is a security risk (so don't do it 😄). 

```js
import toFactory from 'to-factory'
import DocsSearchBar from './DocsSearchBar'
import { version } from '../../package.json'

const docsSearchBar = toFactory(DocsSearchBar)
docsSearchBar.version = version

console.log(docsSearchBar.version)

export default docsSearchBar
```

[genversion](https://www.npmjs.com/package/genversion) is an npm package that gets the version from the `package.json` and generates a `version.js` file without sending any of the other information removing the security issue. I have never used this package myself so I can't vouch for how well it works, but I mention it because it seems as though it could solve your issue.

**Comment by bidoubiwa** [comment]
@sanders41 You are right! Closing this :)
