### ISSUE TITLE
Add a scrolling system to see further results

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/docs-searchbar.js#532]
**Description**
Search is limited to X first results.
We should be able to scroll inside the popup to see other results

**Comment by ColinFrick** [comment]
Any suggestion how this should be implemented?

Because the results could be sorted by relevancy and not by hierarchy, how should the items be added to the popup? Would the headers be duplicated?

F.e with query 'createdAt key' on the meilisearch documentation:
---- First 5 results ----

1. API reference - Keys - Key object - createdAt
2. API reference - Keys - Get all keys - Example
3. API reference - Keys - Create a key - Example
4. API reference - Keys - Get all keys
5. Security and permissions - Master key and API keys - Using the master key to manage API keys - Listing API keys

![image](https://user-images.githubusercontent.com/5517677/193775331-9dca6391-bfa0-4757-8a34-98a0c98ff415.png)

--- Next 5 results ---

1. Security and permissions - Master key and API keys - Communicating with a protected instance - Using default API keys for authorization
2. Security and permissions - ...
3. Cookbooks Deployment - ...
4. **API reference - Indexes - Index object** <- How should this result be displayed in the popup?
5. Configuration - ...

**Comment by bidoubiwa** [comment]
This is a very good point you are raising @ColinFrick. There is also the issue that scrolling would conflict with scrolling on the page itself.

I checked how algolia handles it and they did not add the scrolling possibility. [See example](https://docs.strapi.io/developer-docs/latest/getting-started/introduction.html#open-source-contribution)

This might not be a very good idea after all.

**Comment by bidoubiwa** [comment]
I'm closing this as it is not a good idea!
