### ISSUE TITLE
Update image inside of README with latest Meilisearch logo 

### ISSUE THREAD

**Issue by shivaylamba** [meilisearch/docs-searchbar.js#638]
Update image inside of README with latest Meilisearch logo. Currently it shows the old logo 
![image](https://user-images.githubusercontent.com/19529592/188811020-0ace5f6d-f49e-4b6c-a18a-a4c3ae497f6a.png)

**Comment by bidoubiwa** [comment]
Thanks for spotting this!

**Comment by bidoubiwa** [comment]
Currently, the image is already present in the code. What is missing is a new screen shot with the logo. You can achieve that by running the playground and add some relevant documents in the [setup file](https://github.com/meilisearch/docs-searchbar.js/blob/main/playgrounds/html/setup.js).

**Comment by Shoray2002** [comment]
Hey can I tackle this issue?

**Comment by bidoubiwa** [comment]
Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!

We prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the real volunteers contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/README.md). 

We are looking forward to reviewing your PR 😊
